src/Entity/Abscence.php
<?php

namespace App\Entity;

use App\Repository\AbscenceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AbscenceRepository::class)
 */
class Abscence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reason;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=Student::class, inversedBy="abscences")
     * @ORM\JoinColumn(nullable=false)
     */
    private $student;

    public function __toString() {
        return $this->student;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $LastName;

    /**
     * @ORM\OneToMany(targetEntity=Group::class, mappedBy="User", orphanRemoval=true)
     */
    private $groups;

    public function __construct()
    {
        $this->groups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    /**
     * @return Collection|Group[]
     */
    public function getGroups(): Collection
    {
        return $this->groups;
    }

    public function addGroup(Group $group): self
    {
        if (!$this->groups->contains($group)) {
            $this->groups[] = $group;
            $group->setUser($this);
        }

        return $this;
    }

    public function removeGroup(Group $group): self
    {
        if ($this->groups->removeElement($group)) {
            // set the owning side to null (unless already changed)
            if ($group->getUser() === $this) {
                $group->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/AbscenceType.php
<?php

namespace App\Form;

use App\Entity\Abscence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AbscenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reason', null, ['label'=> 'Raison :'])
            ->add('date', DateType::class , ['label'=> 'Date :'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Abscence::class,
        ]);
    }
}

src/Controller/AbscenceController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Entity\Abscence;
use App\Form\AbscenceType;
use App\Repository\AbscenceRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/abscence")
 */
class AbscenceController extends AbstractController
{
    
    /**
     * @Route("/{id}", name="abscence_index", methods={"GET"})
     */
    public function index(Student $student): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('abscence/index.html.twig', [
            'abscences' => $student->getAbscences(),
            'student' => $student,
        ]);
    }

    /**
     * @Route("/{id}/new", name="abscence_new", methods={"GET","POST"})
     */
    public function new(Request $request, Student $student): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $abscence = new Abscence();
        $form = $this->createForm(AbscenceType::class, $abscence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $abscence->setStudent($student);
            $entityManager->persist($abscence);
            $entityManager->flush();

            return $this->redirectToRoute('abscence_index', ["id"=> $student->getId()]);
        }

        return $this->render('abscence/new.html.twig', [
            'abscence' => $abscence,
            'form' => $form->createView(),
            'student' => $student
        ]);
    }

    /**
     * @Route("/{id}", name="abscence_show", methods={"GET"})
     */
    public function show(Abscence $abscence): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('abscence/show.html.twig', [
            'abscence' => $abscence,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="abscence_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Abscence $abscence): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $form = $this->createForm(AbscenceType::class, $abscence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('abscence_index', ["id"=> $abscence->getStudent()->getId()]);
        }

        return $this->render('abscence/edit.html.twig', [
            'abscence' => $abscence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="abscence_delete", methods={"POST"})
     */
    public function delete(Request $request, Abscence $abscence): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->isCsrfTokenValid('delete'.$abscence->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($abscence);
            $entityManager->flush();
        }

        return $this->redirectToRoute('abscence_index', ["id"=> $abscence->getStudent()->getId()]);
    }
}

templates/abscence/_delete_form.html.twig
<form method="post" action="{{ path('abscence_delete', {'id': abscence.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette sanction ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ abscence.id) }}">
    <button class="btn btn-danger btn-sm">Supprimer</button>
</form>

templates/abscence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="btn-group">
    {% if abscence.student %}
        <a href="{{ path('abscence_index', {'id': abscence.student.id}) }}" class="btn btn-danger"><i class="bi bi-arrow-left"></i> Retour</a>
    {% else %}
        <a href="{{ path('abscence_index', {"id": student.id}) }}" class="btn btn-danger"><i class="bi bi-arrow-left"></i> Retour</a>
    {% endif %}
        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/abscence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Édition d'une abscenc{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Édition d'une abscence</h1>

    {{ include('abscence/_form.html.twig', {'button_label': 'Update'}) }}
</div>
{% endblock %}

templates/abscence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Abscence index{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Liste d'abscences de l'élève : {{student.name}} {{student.lastName}}</h1>

    <a href="{{ path('abscence_new', {"id": student.id}) }}" class="btn btn-primary"><i class="bi bi-plus-circle"></i> Ajouter une abscence</a>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Raison</th>
                <th>Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for abscence in abscences %}
            <tr>
                <td>{{ abscence.reason }}</td>
                <td>{{ abscence.date ? abscence.date|date('Y-m-d H:i:s') : '' }}</td>
                <td class="text-end">
                <div class="btn-group">
                    <a href="{{ path('abscence_edit', {'id': abscence.id}) }}" class="btn btn-primary btn-sm"><i class="bi bi-pencil"></i>Éditer</a>
                    {{ include('abscence/_delete_form.html.twig') }}
                </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Cet élève n'a pas d'abscences</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('student_index', {"id": student.studentGroup.id}) }}" class="btn btn-danger"><i class="bi bi-arrow-left"></i> Retour</a>
</div>
{% endblock %}

templates/abscence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une abscence{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Ajout d'une abscence</h1>

    {{ include('abscence/_form.html.twig') }}
</diV>
{% endblock %}

templates/abscence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Abscence{% endblock %}

{% block body %}
    <h1>Abscence</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ abscence.id }}</td>
            </tr>
            <tr>
                <th>Reason</th>
                <td>{{ abscence.reason }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ abscence.date ? abscence.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('abscence_index') }}">back to list</a>

    <a href="{{ path('abscence_edit', {'id': abscence.id}) }}">edit</a>

    {{ include('abscence/_delete_form.html.twig') }}
{% endblock %}